name: Build

on: [push]


jobs:
  linux:
    strategy:
      matrix:
        version: [8, 11, 16, 17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          architecture: x64
      - run: ./gradlew build --no-daemon

  windows:
    strategy:
      matrix:
        version: [8, 11, 16, 17]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
          architecture: x64
      - run: .\gradlew.bat build --no-daemon

